package cloud.pablos.overload.ui.theme

import androidx.compose.ui.graphics.Color

// Generate them via theme builder
// https://material-foundation.github.io/material-theme-builder/#/custom

val overloadLightPrimary = Color(0xFF825500)
val overloadLightOnPrimary = Color(0xFFFFFFFF)
val overloadLightPrimaryContainer = Color(0xFFFFDDAE)
val overloadLightOnPrimaryContainer = Color(0xFF2A1800)
val overloadLightSecondary = Color(0xFF6F5B40)
val overloadLightOnSecondary = Color(0xFFFFFFFF)
val overloadLightSecondaryContainer = Color(0xFFFADEBC)
val overloadLightOnSecondaryContainer = Color(0xFF271904)
val overloadLightTertiary = Color(0xFF516440)
val overloadLightOnTertiary = Color(0xFFFFFFFF)
val overloadLightTertiaryContainer = Color(0xFFD3EABC)
val overloadLightOnTertiaryContainer = Color(0xFF102004)
val overloadLightError = Color(0xFFBA1B1B)
val overloadLightErrorContainer = Color(0xFFFFDAD4)
val overloadLightOnError = Color(0xFFFFFFFF)
val overloadLightOnErrorContainer = Color(0xFF410001)
val overloadLightBackground = Color(0xFFFCFCFC)
val overloadLightOnBackground = Color(0xFF1F1B16)
val overloadLightSurface = Color(0xFFFCFCFC)
val overloadLightOnSurface = Color(0xFF1F1B16)
val overloadLightSurfaceVariant = Color(0xFFF0E0CF)
val overloadLightOnSurfaceVariant = Color(0xFF4F4539)
val overloadLightOutline = Color(0xFF817567)
val overloadLightInverseOnSurface = Color(0xFFF9EFE6)
val overloadLightInverseSurface = Color(0xFF34302A)
val overloadLightPrimaryInverse = Color(0xFFFFB945)

val overloadDarkPrimary = Color(0xFFFFB945)
val overloadDarkOnPrimary = Color(0xFF452B00)
val overloadDarkPrimaryContainer = Color(0xFF624000)
val overloadDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val overloadDarkSecondary = Color(0xFFDDC3A2)
val overloadDarkOnSecondary = Color(0xFF3E2E16)
val overloadDarkSecondaryContainer = Color(0xFF56442B)
val overloadDarkOnSecondaryContainer = Color(0xFFFADEBC)
val overloadDarkTertiary = Color(0xFFB8CEA2)
val overloadDarkOnTertiary = Color(0xFF243516)
val overloadDarkTertiaryContainer = Color(0xFF3A4C2B)
val overloadDarkOnTertiaryContainer = Color(0xFFD3EABC)
val overloadDarkError = Color(0xFFFFB4A9)
val overloadDarkErrorContainer = Color(0xFF930006)
val overloadDarkOnError = Color(0xFF680003)
val overloadDarkOnErrorContainer = Color(0xFFFFDAD4)
val overloadDarkBackground = Color(0xFF1F1B16)
val overloadDarkOnBackground = Color(0xFFEAE1D9)
val overloadDarkSurface = Color(0xFF1F1B16)
val overloadDarkOnSurface = Color(0xFFEAE1D9)
val overloadDarkSurfaceVariant = Color(0xFF4F4539)
val overloadDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val overloadDarkOutline = Color(0xFF9C8F80)
val overloadDarkInverseOnSurface = Color(0xFF32281A)
val overloadDarkInverseSurface = Color(0xFFEAE1D9)
val overloadDarkPrimaryInverse = Color(0xFF624000)
